### ISSUE TITLE
Attempted import error: 'AppWrapper' is not exported from './components/wrapper'.

### ISSUE THREAD

**Issue by tejasamandaliya** [MathewsJoseph25/create-shopify-app#1]
![Screenshot 2020-09-12 at 2 04 37 PM](https://user-images.githubusercontent.com/26873822/92991351-e7717900-f500-11ea-8bdb-98a48312870d.png)

Hey,

Thanks For sharing the code,

Can you please check why I am getting this error.

Thanks 
Tejas

**Comment by MathewsJoseph25** [comment]
Hey Tejas! Thank you for flagging this. I honestly don't know how this issue popped up, but to fix this, you just have to change the import statement on the _app.js file 
from:
import {AppWrapper} from "./components/wrapper";
to
import AppWrapper from "./components/wrapper";

I have updated the repo with the fix. So, if you want you can clone again.

**Comment by tejasamandaliya** [comment]
Hey, @MathewsJoseph25 Thanks for the response.

Yes, it's working now after removing braces.
