### ISSUE TITLE
What values should I use for shopify_redirect_uri and shopify_webhook_uri?

### ISSUE THREAD

**Issue by marcoamonteiro** [MathewsJoseph25/create-shopify-app#4]
Hi, how can I find or generate the following environment variables?

DEV_SHOPIFY_REDIRECT_URI
DEV_SHOPIFY_WEBHOOK_URI

**Comment by MathewsJoseph25** [comment]
Hey @marcoamonteiro That depends on the ngrok url you have initiated on your system. It should be something like:

DEV_SHOPIFY_REDIRECT_URI = https://{ngrok_hostname}/auth/callback
DEV_SHOPIFY_WEBHOOK_URI = https://{{ngrok_hostname}}/webhooks

So, for example, if the ngrok url is testing.ngrok.io, then those should be 

DEV_SHOPIFY_REDIRECT_URI = https://testing.ngrok.io/auth/callback
DEV_SHOPIFY_WEBHOOK_URI = https://testing.ngrok.io/webhooks
