### ISSUE TITLE
The app couldn’t be loaded  This app can’t load due to an issue with browser cookies. 

### ISSUE THREAD

**Issue by marcoamonteiro** [MathewsJoseph25/create-shopify-app#5]
I followed the setup steps in the README and used mongodb. When I go to actually install the app on a development store I see the following error.`The app couldn’t be loaded. This app can’t load due to an issue with browser cookies. `

Looking at network traffic it seems the last request is to <ngrok>/auth/callbacks and the response tried setting the following cookies:

```
set-cookie: _y=<>; Expires=Thu, 18-Aug-22 19:37:01 GMT; Domain=shopifycloud.com; Path=/; SameSite=Lax
set-cookie: _s=<>; Expires=Wed, 18-Aug-21 20:07:01 GMT; Domain=shopifycloud.com; Path=/; SameSite=Lax
set-cookie: _shopify_y=<>; Expires=Thu, 18-Aug-22 19:37:01 GMT; Domain=shopifycloud.com; Path=/; SameSite=Lax
set-cookie: _shopify_s=<>; Expires=Wed, 18-Aug-21 20:07:01 GMT; Domain=shopifycloud.com; Path=/; SameSite=Lax
```

Also I looked in my mongo db database and an entry was made for the store.

**Comment by marcoamonteiro** [comment]
Bumping this, have tried debugging it quite a bit with no progress. Any input would be helpful. Thanks!

**Comment by MathewsJoseph25** [comment]
Hey @marcoamonteiro Well! That's new. I didn't face that issue yet. What happens if you go back to the admin and then try to open the app from the apps section? Does it throw that error there or not?

**Comment by marcoamonteiro** [comment]
yeah, it still throws the error if I try opening from the admin

**Comment by MathewsJoseph25** [comment]
This has been fixed in the latest update.
